import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SeasionProvide from "./Components/SeasionProvide";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('../../public/assets/mainbg2.png')] bg-cover bg-center bg-no-repeat`}
      >
        <SeasionProvide>
          <Nav />
          {children}
        </SeasionProvide>
        <Footer />
      </body>
    </html>
  );
}
